//  ------------------------------------------------------------------------------------
// Copyright (c) Dishant Langayan
// All rights reserved. 
// 
// Licensed under the Apache License, Version 2.0 (the ""License""); you may not use this 
// file except in compliance with the License. You may obtain a copy of the License at 
// http://www.apache.org/licenses/LICENSE-2.0  
// 
// THIS CODE IS PROVIDED *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
// EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTIES OR 
// CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABLITY OR 
// NON-INFRINGEMENT. 
// 
// See the Apache Version 2.0 License for specific language governing permissions and 
// limitations under the License.
//  ------------------------------------------------------------------------------------

using System;

namespace SolaceDotNetWrapper.Core
{
    public enum FlowState
    {
        /// <summary>
        /// The flow is established.
        /// </summary>
        Up = 0,
        /// <summary>
        /// The flow was established and then disconnected by the Solace Event Broker, likely due to operator intervention.
        /// </summary>
        Down = 1,
        /// <summary>
        /// The flow attempted to connect but was unsuccessful.
        /// </summary>
        BindFailedError = 2,
        /// <summary>
        /// The flow is active. This event is generated by the API when the flow is immediately active after creation or when the flow later becomes active.
        /// </summary>
        FlowActive = 3,
        /// <summary>
        /// The flow is inactive. This event is generated by the API when the flow becomes inactive.
        /// </summary>
        FlowInactive = 4
    }
}
