//  ------------------------------------------------------------------------------------
// Copyright (c) Dishant Langayan
// All rights reserved. 
// 
// Licensed under the Apache License, Version 2.0 (the ""License""); you may not use this 
// file except in compliance with the License. You may obtain a copy of the License at 
// http://www.apache.org/licenses/LICENSE-2.0  
// 
// THIS CODE IS PROVIDED *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
// EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTIES OR 
// CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABLITY OR 
// NON-INFRINGEMENT. 
// 
// See the Apache Version 2.0 License for specific language governing permissions and 
// limitations under the License.
//  ------------------------------------------------------------------------------------

using System;

namespace SolaceDotNetWrapper.Core
{
    /// <summary>
    ///     Headers in the Wrapper Message
    /// </summary>
    public enum SolaceHeaders
    {
        /// <summary>
        ///     Publisher can set this property on a Guaranteed message to request the Solace the appliance to acknowledge the receipt of the message immediately, as opposed to waiting for the message to be spooled on the appliance and then acknowledge it.
        /// </summary>
        SOL_AckImmediately,

        /// <summary>
        ///     Applies to received messages only with DeliveryMode MessageDeliveryMode.PERSISTENT or MessageDeliveryMode.NON_PERSISTENT. Represents the message Id of a Guaranteed message and can be used when acknowledging such a message. If not available 0 is returned.
        /// </summary>
        SOL_AdMessageId,

        /// <summary>
        ///     Gets/sets the application messageId. Returns null if not present.
        /// </summary>
        SOL_ApplicationMessageId,

        /// <summary>
        ///     Gets/sets the application message type. This value is used by applications only and is passed through the API untouched. If not present, null is returned.
        /// </summary>
        SOL_ApplicationMessageType,

        /// <summary>
        ///     Returns the request ID set in the cache request. Always null if CacheStatus is MessageCacheStatus.Live If not present -1 is returned
        /// </summary>
        SOL_CacheRequestId,

        /// <summary>
        ///     The correlation id is used for correlating a request to a reply. If not present, null is returned.
        /// </summary>
        SOL_CorrelationId,

        /// <summary>
        ///     A setter/getter for the Deliver-To-One (DTO) property on a message with a Delivery mode of Direct. When a message has the DTO property set, it can to be delivered only to one client. T
        /// </summary>
        SOL_DeliverToOne,

        /// <summary>
        ///     Returns true if one or more messages have been discarded prior to the current message, otherwise it returns false. Indicates congestion discards only and is not affected by message eliding.
        /// </summary>
        SOL_DiscardIndication,

        /// <summary>
        ///     Expired messages with this property set to true are moved to a Dead Message Queue when one is provisioned on the router. Default: false
        /// </summary>
        SOL_DmqEligible,

        /// <summary>
        ///     Setting this property to true indicates that this message should be eligible for eliding.
        /// </summary>
        SOL_ElidingEligible,

        /// <summary>
        ///     Returns true if it is a reply message (reply to a request).
        /// </summary>
        SOL_IsReplyMessage,

        /// <summary>
        ///     Gets the receive timestamp (in milliseconds, from midnight, January 1, 1970 UTC). Returns -1 if not present.
        /// </summary>
        SOL_ReceiverTimestamp,

        /// <summary>
        ///     Applies only when DeliveryMode is MessageDeliveryMode.PERSISTENT or MessageDeliveryMode.NON_PERSISTENT. Indicates if the message has been delivered by the router to the API before.
        /// </summary>
        SOL_Redelivered,

        /// <summary>
        ///     Represents the sender id. Returns null if not present.
        /// </summary>
        SOL_SenderId,

        /// <summary>
        ///     Gets the sender timestamp (in milliseconds, from midnight, January 1, 1970 UTC). Returns -1 if not present or set.
        /// </summary>
        SOL_SenderTimestamp,

        /// <summary>
        ///     Represents the message sequence number. The set operation overrides the sequence number automatically generated by the session (if set). Returns null if not present.
        /// </summary>
        SOL_SequenceNumber,

        /// <summary>
        ///     The number of milliseconds before the message is discarded or moved to a Dead Message Queue. A value of 0 means the message never expires. The default value is zero. Note that this property is only valid for Guaranteed Delivery messages (Persistent and Non-Persistent). It has no effect when used in conjunction with other message types unless the message is promoted by the router to a Guaranteed Delivery message.
        /// </summary>
        SOL_TimeToLive,

        /// <summary>
        ///     The user data part of the message (maximum: 36 bytes). Returns null if not present.
        /// </summary>
        SOL_UserData
    }
}
